from pathlib import Path
from typing import BinaryIO, Protocol


class StorageAdapter(Protocol):
    def put_file(self, key: str, path: Path) -> None: ...

    def open(self, key: str) -> BinaryIO: ...

    def delete(self, key: str) -> None: ...

    def exists(self, key: str) -> bool: ...
